version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-2:860061945305:task-definition/888336-HappyReturnsTask:3"
        LoadBalancerInfo:
          ContainerName: "namingservice"
          ContainerPort: "9002"
        PlatformVersion: "LATEST"
